# Section A: Data Structures & Control Structures

In [14]:
# Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse

num = [1,2,3,4,5]
#append
num.append(6)
print("Append: ",num)

# extend
num.extend([7,8])
print("Extend: ",num)
# insert
num.insert(2,10)
print("Insert: ",num)
#remove
num.remove(8)
print("Remove: ",num)
#pop
num.pop()
print("Pop: ",num)
#index
print("Index of 10: ",num.index(10))
#count
print("Count: ",num.count(2))
#sort
num.sort()
print("Sort: ",num)
#reverse
num.reverse()
print("Reverse: ",num)


Append:  [1, 2, 3, 4, 5, 6]
Extend:  [1, 2, 3, 4, 5, 6, 7, 8]
Insert:  [1, 2, 10, 3, 4, 5, 6, 7, 8]
Remove:  [1, 2, 10, 3, 4, 5, 6, 7]
Pop:  [1, 2, 10, 3, 4, 5, 6]
Index of 10:  2
Count:  1
Sort:  [1, 2, 3, 4, 5, 6, 10]
Reverse:  [10, 6, 5, 4, 3, 2, 1]


In [15]:
# Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
tup1 = ("mitali","nitin","patil")
tup1[1]="Priya"
print(tup1)


TypeError: 'tuple' object does not support item assignment

In [ ]:
# Create a set of integers with some duplicate values. Print the set and explain the output.
int1={1,2,3,4,5,6,1,2,7,8,9}
print("Interger: ",int1)
#A set automatically removes duplicate values, so each number appears only once.

In [ ]:
# Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
dict = {
    "name" :"Mitali",
    "age"  : "25",
    "city" : "Mumbai"
}
#update age
dict ["age"]=24
#add email
dict["email"] = "mitalipatiln@gmail.com"
print(dict)

In [18]:
# Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
age = int(input("Enter Your age: "))
if age >= 18:
    print("Eligible")
else:
    print("Not Eligible")
    


Enter Your age:  34


Eligible


In [5]:
# Given a 'marks' variable, print the grade

marks  = int(input("Enter marks: "))
if marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >=50:
    print("C")
else :
    print("Fail")



Enter marks:  65


C


In [6]:
# Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative
number = int(input("Enter Number: "))
if number > 0:
    print("Positive")
    if number % 2 == 0:
        print("Even number")
    else:
        print("Odd number")
elif num == 0:
    print("Number is zero")
else:
    print("Negative")


Enter Number:  45


Positive
Odd number


## Section B: Numpy


In [9]:
import numpy as np 
# scalar
scalar = np.array(5)
print("Scalar: ", scalar)

# 1D array with 1 to 5
arr1 = np.array([1,2,3,4,5])
print("1D Array: ",arr1)

#A 2D array (2x3) with values from 10 to 60 in steps of 10
arr2 = np.array([[10,20,30],
                  [40,50,60]])
print("2D Array:\n ",arr2)


Scalar:  5
1D Array:  [1 2 3 4 5]
2D Array:
  [[10 20 30]
 [40 50 60]]


In [12]:
# Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
import numpy as np 
random_arr = np.random.randint(0,101,(4,4))
print("Random array:\n ",random_arr)

Random array:
  [[95 69 78 61]
 [71  6  2 73]
 [23 97  2 91]
 [26 70 69 33]]


In [16]:
# Convert NumPy Array to Pandas DataFrame
import numpy as np 
import pandas as pd
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
df = pd.DataFrame(array, columns=['A','B','C'])
print(df)
                  


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


## Section C: Exploring Pandas

In [20]:
# Create DataFrame and Perform Operations
import pandas as pd 
data = {
    'Name' :['Mitali','Pooja','Snehal','Jyoti','Bhagshree','Krutika','Vrushali','Radha','Himani','Nidhi'],
    'Age' : ['23','24','25','26','27','28','29','30','31','32'],
    'City': ['Mumbai','Pune','Banglore','Chennai','Mumbai','Pune','Nasik','Mumbai','Pune','Mumbai'],
    'Salary':['25000','24000','10000','30000','none','20000','230000','240000','30000','30000']
}
df = pd.DataFrame(data)
print(df)

        Name Age      City  Salary
0     Mitali  23    Mumbai   25000
1      Pooja  24      Pune   24000
2     Snehal  25  Banglore   10000
3      Jyoti  26   Chennai   30000
4  Bhagshree  27    Mumbai    none
5    Krutika  28      Pune   20000
6   Vrushali  29     Nasik  230000
7      Radha  30    Mumbai  240000
8     Himani  31      Pune   30000
9      Nidhi  32    Mumbai   30000


In [21]:
# Use .info(), .describe()
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     object
 2   City    10 non-null     object
 3   Salary  10 non-null     object
dtypes: object(4)
memory usage: 452.0+ bytes
None
          Name Age    City Salary
count       10  10      10     10
unique      10  10       5      8
top     Mitali  23  Mumbai  30000
freq         1   1       4      3


In [24]:
# Select 'Name' and 'City' columns
print(df[['Name','City']])

        Name      City
0     Mitali    Mumbai
1      Pooja      Pune
2     Snehal  Banglore
3      Jyoti   Chennai
4  Bhagshree    Mumbai
5    Krutika      Pune
6   Vrushali     Nasik
7      Radha    Mumbai
8     Himani      Pune
9      Nidhi    Mumbai


In [27]:
# Drop 'City' column
df =df.drop('City', axis = 1)
print(df)

        Name Age  Salary
0     Mitali  23   25000
1      Pooja  24   24000
2     Snehal  25   10000
3      Jyoti  26   30000
4  Bhagshree  27    none
5    Krutika  28   20000
6   Vrushali  29  230000
7      Radha  30  240000
8     Himani  31   30000
9      Nidhi  32   30000


In [31]:
#  Fill any missing values in 'Salary' column with the mean
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
print(df['Salary'])


0     25000.0
1     24000.0
2     10000.0
3     30000.0
4     71000.0
5     20000.0
6    230000.0
7    240000.0
8     30000.0
9     30000.0
Name: Salary, dtype: float64


In [33]:
#  Remove any duplicate rows
df= df.drop_duplicates()
print(df)

        Name Age    Salary
0     Mitali  23   25000.0
1      Pooja  24   24000.0
2     Snehal  25   10000.0
3      Jyoti  26   30000.0
4  Bhagshree  27   71000.0
5    Krutika  28   20000.0
6   Vrushali  29  230000.0
7      Radha  30  240000.0
8     Himani  31   30000.0
9      Nidhi  32   30000.0
